### ISSUE TITLE
Proliferation max MK.2  (2dots)

### ISSUE THREAD

**Issue by TheToolGuy** [nolimet/DysonSphereMods#3]
It creates products 4 stacks high, very fine,  but only at proliferation MK.2 (2 dots) as a max ...

NOT  proliferation MK.3 (3 dots),     whatever I change in the config file ...

Could you fix that please ?

**Comment by nolimet** [comment]
Will look into this.

**Comment by nolimet** [comment]
Mod has been updated. Uncapped the value. You can now set it as high as you want.
You change how many points are applied to it.. I think.
But 16 should get you close to the 100% value
Or go for broke and set it to 255 which can give you a boost of 250%

**Comment by TheToolGuy** [comment]
👍
